"""add shop_profiles

Revision ID: 0e28db023e8e
Revises: 983fd253538a
Create Date: 2026-02-22 17:42:34.313360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e28db023e8e'
down_revision: Union[str, Sequence[str], None] = '983fd253538a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_profiles',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('hours', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=120), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('shop_id')
    )
    op.create_index(op.f('ix_shop_profiles_shop_id'), 'shop_profiles', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_profiles_shop_id'), table_name='shop_profiles')
    op.drop_table('shop_profiles')
    # ### end Alembic commands ###
